name: nlp-ood
dependencies:
  - python==3.9
  - numpy
  - pandas>=0.23
  - scikit-learn>=0.20
  - matplotlib
  - seaborn
  - jupyter
  - scipy
  - datasets
  - pip
  - pip:
      - torch
      - transformers==4.26.1
      - kaggle
