name: nlp-ood
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - pandas>=0.23
  - scikit-learn>=0.20
  - matplotlib
  - seaborn
  - jupyter
  - scipy
  - kaggle
  - transformers==4.26.1
  - datasets
  - pip
  - pip:
      - torch
